apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oekwetter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/oererenn/kwetter.git
    targetRevision: HEAD
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: kwetter
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true

