apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: user
  namespace: kwetter
  annotations:
    kubernetes.io/ingress.class: kong
username: apiUser
credentials:
  - apiuser-apikey