apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: timeline-service-hpa
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: timeline-service-deployment
  targetCPUUtilizationPercentage: 35
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kweet-service-hpa
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kweet-service-deployment
  targetCPUUtilizationPercentage: 25
