apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: user-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-secret
                  key: client-id
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: azure-secret
                  key: client-secret
            - name: TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-secret
                  key: tenant-id
            - name: END_POINT
              valueFrom:
                secretKeyRef:
                  name: azure-secret
                  key: end-point
      restartPolicy: Always
  selector:
    matchLabels:
      app: user-service
