name: Maven CI/CD Timeline Service

on:
  push:
    paths:
      - 'timeline-service/**'
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      env: 
          CLIENT_ID: '${{secrets.CLIENT_ID}}'
          CLIENT_SECRET: '${{secrets.CLIENT_SECRET}}'
          END_POINT: '${{secrets.END_POINT}}'
          TENANT_ID: '${{secrets.TENANT_ID}}'
      run: mvn -B package --file timeline-service/pom.xml
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: "timeline-service"
        push: true
        tags: oereren/timeline-service:${{ github.sha }}
             
    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "3.6.1"

    - name: Update Kubernetes resources
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      run: |
       cd kustomize/base
       kustomize edit set image timeline-service=$DOCKERHUB_USERNAME/timeline-service:$GITHUB_SHA
       cat kustomization.yaml
        
    - name: Commit and files
      run: |
        git config --local user.name "$(git log -n 1 --pretty=format:%an)"
        git config --local user.email "$(git log -n 1 --pretty=format:%ae)"
        git stash
        git pull
        git stash apply
        git add .
        git commit -am "Updated Timeline Service Image Tag"
        git push

